// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PostUmbracoManagementApiV1MemberLoginLoginData, PostUmbracoManagementApiV1MemberLoginLoginErrors, PostUmbracoManagementApiV1MemberLoginLoginResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class V1 {
    public static postUmbracoManagementApiV1MemberLoginLogin<ThrowOnError extends boolean = false>(options?: Options<PostUmbracoManagementApiV1MemberLoginLoginData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoManagementApiV1MemberLoginLoginResponses, PostUmbracoManagementApiV1MemberLoginLoginErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/member-login/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}
