// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44307' | (string & {});
};

export type MemberLoginRequestModel = {
    memberKey: string;
    contentKey?: string | null;
    culture?: string | null;
};

export type MemberLoginResponseModel = {
    redirectUrl: string;
};

export type PostUmbracoManagementApiV1MemberLoginLoginData = {
    body?: MemberLoginRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/member-login/login';
};

export type PostUmbracoManagementApiV1MemberLoginLoginErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostUmbracoManagementApiV1MemberLoginLoginResponses = {
    /**
     * OK
     */
    200: MemberLoginResponseModel;
};

export type PostUmbracoManagementApiV1MemberLoginLoginResponse = PostUmbracoManagementApiV1MemberLoginLoginResponses[keyof PostUmbracoManagementApiV1MemberLoginLoginResponses];
